---
- hosts: localhost
  vars:
  tasks:
  - name: Checkout code from github
    git:
      repo: https://github.com/admiyo/GhoulWebApp.git
      dest: /tmp/GhoulWebApp

  - name: Enable a RHSM repository
    rhsm_repository:
      name: rhel-server-rhscl-7-rpms

  - name: install the Maven Software collection
    yum:
      name: rh-maven35
      state: latest

  - name: build the war file
    shell: scl enable rh-maven35  "mvn package"
    args:
      chdir:  /tmp/GhoulWebApp


- hosts: dev1jboss.awx.devstack
  vars:
    check_version: "1.1.*"
  remote_user: cloud-user
  become: yes
  become_user: root
  tasks:

  - name: deploy the war file
    copy:
      src: /tmp/GhoulWebApp/target/GhoulWebApp.war
      dest: /var/opt/rh/eap7/lib/wildfly/standalone/deployments/
      owner: root
      group: jboss
      mode: 0644

  - name: Check Deployment
    uri:
      url: http://localhost:8080/GhoulWebApp/
      return_content: yes
    register: webpage

  - debug:
      msg: "{{ webpage.json }}"

  - name: Fail if  check_version is not in the page content
    fail:
    when: webpage.json.Version is not match(check_version)

